#server:
 # port: 8761
  #servlet:
   # context-path: "/eureka"


spring:
  application:
    name: eureka

# For Eureka Server
logging:
  level:
    org.springframework.cloud.netflix.eureka.server: DEBUG

#eureka:
  #client:
   # registerWithEureka: true
    #fetchRegistry: true
    #service-url:
     # defaultZone: http://localhost:8761/eureka/

server:
  port: 8761
  servlet:
    #context-path: "/eureka"
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging.level.org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"