server:
  port: 8081
  servlet:
    context-path: "/first-service"

spring:
  application:
    name: myClientApp

eureka:
  instance:
    name: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging.level.org.springframework: INFO


management:
  endpoints:
    web:
      exposure:
        include: "*"